[aws]
disabled = true

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 8

[gcloud]
disabled = true

[git_branch]
style = "242"

[username]
disabled = false

[hostname]
ssh_only = false
style = "bold green"
disabled = true

[kubernetes]
disabled = true

[python]
disabled = true

[container]
disabled = true

[ruby]
disabled = true
