#!/bin/bash
# Set the number of workspaces
bspc monitor HDMI-0 -d 1 2 3 4 5 6
bspc monitor DVI-D-0 -d 7 8 9 10

# Launch keybindings daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Window configurations
bspc config border_width 0
bspc config window_gap 5
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Padding outside of the window
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# Move floating windows
bspc config pointer_action1 move

# Resize floating windows
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Set background and top bar

dunst &
picom &
polybar -c ~/.config/polybar/config.ini &
