[font]
size = 10

[font.normal]
#family = "CaskaydiaCove Nerd Font"
family = "JetBrains Mono Nerd Font"
#family = "VictorMono Nerd Font "
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 0
y = 0

[colors.primary]
background = '#10100E'
foreground = '#C6C6C4'

[colors.normal]
black   = '#10100E'
red     = '#C40233'
green   = '#009F6B'
yellow  = '#FFD700'
blue    = '#0087BD'
magenta = '#9A4EAE'
cyan    = '#20B2AA'
white   = '#C6C6C4'

[colors.bright]
black   = '#696969'
red     = '#FF2400'
green   = '#03C03C'
yellow  = '#FDFF00'
blue    = '#007FFF'
magenta = '#FF1493'
cyan    = '#00CCCC'
white   = '#FFFAFA'

# [colors.primary]
# background = '#2E3440'
# foreground = '#D8DEE9'
#
# [colors.normal]
# black   = '#3B4252'
# red     = '#BF616A'
# green   = '#A3BE8C'
# yellow  = '#EBCB8B'
# blue    = '#81A1C1'
# magenta = '#B48EAD'
# cyan    = '#88C0D0'
# white   = '#E5E9F0'
#
# [colors.bright]
# black   = '#4C566A'
# red     = '#BF616A'
# green   = '#A3BE8C'
# yellow  = '#EBCB8B'
# blue    = '#81A1C1'
# magenta = '#B48EAD'
# cyan    = '#8FBCBB'
# white   = '#ECEFF4'
